### ISSUE TITLE
Sweep: Write tests for write/lib/summary/on_new_day.rb

### ISSUE THREAD

**Issue by nicieja** [changepack/changepack#141]
Write tests for write/lib/summary/on_new_day.rb

**Comment by wwzeng1** [comment]
I don’t think this is the correct way to proceed. Summary::OnNewDay’s job is to publish an event called Summary::Requested. We already have a handler for that event (Summary::OnRequested at write/lib/summary/on_requested.rb). We could add a spec for that event handler too. Summary::OnRequested calls the Summary model and saves it, but that doesn’t need to be tested since we already have write/spec/models/summary_spec.rb.
